from typing import Final


GREETING_STICKER: Final[str] = 'CAACAgIAAxkBAAEQNB1pYL_MbFzbtinFJHGCSYXsVnjk5QAC2A8AAkjyYEsV-8TaeHRrmDgE'
PLUG_STICKER: Final[str] = 'CAACAgIAAxkBAAEQNB9pYMBUxvreBYRJmO360xlbTnCXrgACJg4AAvW6EEiEWDQIzqqeEzgE'
NO_NOTICES_STICKER: Final[str] = 'CAACAgIAAxkBAAEQNCFpYMFJJs-Q2m16irKphzGB1irH1gACPQ0AAoycEUi5TfuqIQH5RjgE'
