global:
  resolve_timeout: 5m

route:
  receiver: email-default
  group_by:
    - alertname
    - severity
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - match:
        severity: critical
      receiver: email-critical

    - match:
        severity: warning
      receiver: email-warning

receivers:
  - name: email-default
    email_configs:
      - to: team@example.ru
        from: alertmanager@example.ru
        smarthost: smtp.example.ru:587
        auth_username: alertmanager@example.ru
        auth_password: APP_PASSWORD
        send_resolved: true

  - name: email-critical
    email_configs:
      - to: oncall@example.ru
        from: alertmanager@example.ru
        smarthost: smtp.example.ru:587
        auth_username: alertmanager@example.ru
        auth_password: APP_PASSWORD
        send_resolved: true

  - name: email-warning
    email_configs:
      - to: team@example.ru
        from: alertmanager@example.ru
        smarthost: smtp.example.ru:587
        auth_username: alertmanager@example.ru
        auth_password: APP_PASSWORD
        send_resolved: true