# Generated by Django 6.0 on 2026-01-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                (
                    'status',
                    models.CharField(
                        choices=[('NEW', 'Новое'), ('COMPLETED', 'Выполнено'), ('DECLINED', 'Отклонено')],
                        default='NEW',
                        max_length=9,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'object_type',
                    models.CharField(
                        choices=[
                            ('USER', 'Пользователь'),
                            ('MISSING_NOTICE', 'Объявление о пропаже питомца'),
                            ('FOUND_NOTICE', 'Объявление о находке питомца'),
                            ('ADOPTION_NOTICE', 'Объявление о пристройстве питомца'),
                        ],
                        max_length=15,
                        verbose_name='Тип объекта',
                    ),
                ),
                ('object_id', models.BigIntegerField(verbose_name='ID объекта')),
                ('text', models.CharField(max_length=150, verbose_name='Текст')),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='complaints',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Создатель',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
