# Generated by Django 6.0 on 2026-01-06 09:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                (
                    'name',
                    models.CharField(
                        max_length=150,
                        validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яёА-ЯЁ\\s\\-]*$')],
                        verbose_name='Имя',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={'unique': 'Пользователь с таким логином уже существует'},
                        max_length=50,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name='Логин',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        error_messages={'unique': 'Пользователь с таким email уже существует'},
                        max_length=254,
                        unique=True,
                        verbose_name='Email',
                    ),
                ),
                (
                    'phone_number',
                    models.CharField(
                        error_messages={'unique': 'Пользователь с таким номером уже существует'},
                        max_length=11,
                        unique=True,
                        validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')],
                        verbose_name='Номер телефона',
                    ),
                ),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Местоположение')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Местоположение пользователя',
                'verbose_name_plural': 'Местоположения пользователей',
            },
        ),
    ]
