# Generated by Django 6.0 on 2026-01-07 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_found_notices', '0001_initial'),
        ('pet_missing_notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetNoticeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                (
                    'match_status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Ожидает рассмотрения'),
                            ('APPROVED', 'Подтверждено совпадение'),
                            ('DECLINED', 'Отклонено'),
                        ],
                        default='PENDING',
                        max_length=8,
                        verbose_name='Статус',
                    ),
                ),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарий')),
                (
                    'found_notice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pet_notice_matches',
                        to='pet_found_notices.petfoundnotice',
                        verbose_name='Объявление о находке питомца',
                    ),
                ),
                (
                    'initiator',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pet_notice_matches',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Владелец',
                    ),
                ),
                (
                    'missing_notice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pet_notice_matches',
                        to='pet_missing_notices.petmissingnotice',
                        verbose_name='Объявление о пропаже питомца',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Совпадение объявлений о питомцах',
                'verbose_name_plural': 'Совпадения объявлений о питомцах',
            },
        ),
    ]
