# Generated by Django 6.0 on 2026-02-01 07:10

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMissingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('pet_name', models.CharField(max_length=30, verbose_name='Кличка питомца')),
                (
                    'pet_species',
                    models.CharField(
                        choices=[('DOG', 'Собака'), ('CAT', 'Кошка'), ('BIRD', 'Птица'), ('OTHER', 'Другое')],
                        max_length=5,
                        verbose_name='Вид питомца',
                    ),
                ),
                ('pet_breed', models.CharField(blank=True, max_length=30, verbose_name='Порода питомца')),
                ('pet_color', models.CharField(max_length=30, verbose_name='Окрас питомца')),
                (
                    'pet_special_marks',
                    models.CharField(blank=True, max_length=100, verbose_name='Особые приметы питомца'),
                ),
                (
                    'pet_sex',
                    models.CharField(
                        choices=[('MALE', 'М'), ('FEMALE', 'Ж'), ('UNKNOWN', 'Неизвестно')],
                        max_length=7,
                        verbose_name='Пол питомца',
                    ),
                ),
                ('pet_age', models.IntegerField(null=True, verbose_name='Возраст питомца')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('NEW', 'Новое'),
                            ('ACTIVE', 'Активное'),
                            ('FOUND', 'Питомец найден'),
                            ('CLOSED', 'Закрыто'),
                            ('BLOCKED', 'Заблокировано'),
                        ],
                        default='NEW',
                        max_length=7,
                        verbose_name='Статус',
                    ),
                ),
                ('lost_datetime', models.DateTimeField(verbose_name='Время пропажи питомца')),
                (
                    'lost_location',
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name='Последнее местоположение питомца'
                    ),
                ),
                (
                    'image',
                    models.FileField(
                        upload_to='pet-missing-notices-photos',
                        validators=[
                            utils.validators.MaxFileSizeValidator(15728640),
                            django.core.validators.FileExtensionValidator(('png', 'bmp', 'jpeg', 'jpg')),
                        ],
                        verbose_name='Фотография',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pet_missing_notices',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Владелец',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Объявление о пропаже питомца',
                'verbose_name_plural': 'Объявления о пропаже питомца',
            },
        ),
    ]
